### ISSUE TITLE
GaussianModel' object has no attribute 'max_radii_plusD

### ISSUE THREAD

**Issue by sam-motamed** [zeng-yifei/STAG4D#3]
Thanks for releasing the code. I am trying to run the minion example and face the following error;

```Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 10.64it/s]
[INFO] loaded zero123!
 12%|████████████▏                                                                                         | 1199/10001 [08:30<1:02:28,  2.35it/s]
Traceback (most recent call last):
  File "main.py", line 1012, in <module>
    gui.train(opt.save_step+1)
  File "main.py", line 984, in train
    self.train_step()
  File "main.py", line 407, in train_step
    self.renderer.gaussians.max_radii_plusD[visibility_filter] = torch.max(self.renderer.gaussians.max_radii_plusD[visibility_filter], radii[visibility_filter])
AttributeError: 'GaussianModel' object has no attribute 'max_radii_plusD'
```

any idea on what the issue is here?

**Comment by sam-motamed** [comment]
Assuming, it is ```gaussians.max_radii2D``` and not ```gaussians.max_radii_plusD```, it leads to the following error:
```
File "main.py", line 407, in train_step
    self.renderer.gaussians.max_radii2D[visibility_filter] = torch.max(self.renderer.gaussians.max_radii2D[visibility_filter], radii[visibility_filter])
IndexError: too many indices for tensor of dimension 1
```

**Comment by zeng-yifei** [comment]
Sorry, that is a small bug that happens after I arrange the code. I have fixed it now.

Thank you very much for reporting it. Feel free to ask me if you have other problems.

**Comment by sam-motamed** [comment]
Thanks for the quick response. There is now a size mismatch error:
```
  File "main.py", line 406, in train_step
    radii = torch.cat(radii_list,0).max(dim=0).values
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 128 for tensor number 1 in the list.
```

I am digging to see how ```render_resolution ``` in main.py should be set but your feedback is much appreciated.

Thanks

**Comment by zeng-yifei** [comment]
How many steps do you run into this error? I have tried running it, but no error occurs like this.

render_resolution is ok with 512/768/1024. For gaussian, it doesn't slow down the process with the improvement of rendering resolution. Actually, you can set this value as you wish. However, as the supervision resolution of diffusion model doesn't achieve such a high value like 1024, it won't be very useful to improve render_resolution after 512/768.

**Comment by zeng-yifei** [comment]
Are you using the /slothfulxtx/diff-gaussian-rasterization as the readme suggests? Or you have changed the Gaussian differentiable rasterizer which you installed in another repo?

I have tried using another diff_gaussian_rasterizer and got an error the same as the first image you presented. Maybe you can check it out.

**Comment by sam-motamed** [comment]
I re-installed diff-gaussian-rasterization and same issue remains. If I comment out the following lines:
```
if self.step >= self.opt.density_start_iter and self.step <= self.opt.density_end_iter:
                self.renderer.gaussians.max_radii2D[visibility_filter] = torch.max(self.renderer.gaussians.max_radii2D[visibility_filter], radii[visibility_filter])
                self.renderer.gaussians.add_densification_stats(viewspace_point_tensor_grad, visibility_filter)
                if self.step % self.opt.densification_interval == 1 :
                    self.renderer.gaussians.densify_and_prune(self.opt.densify_grad_threshold, min_opacity=0.01, extent=1, max_screen_size=2)

```
then I am able to run and get model.ply

**Comment by zeng-yifei** [comment]
Yes, there is certainly something wrong with densification.

I still hope you to check carefully if you installed the **slothfulxtx**'s diff_gauss instead of others'. Because when I switch to dreamgaussian's gs rasterizer, I met the same two errors as you mentioned above. And can you see if the line 10 of gs_renderer_4d.py is `from **diff_gauss** import xxx`.

**Comment by sam-motamed** [comment]
Thanks alot @zeng-yifei , the issue was indeed ```from **diff_gauss** import xxx```! Now I have one hopefully last question; settung ```gui=True``` does not do anything for me. After running main.py, I am left with :
<img width="1144" alt="Screenshot 2024-05-14 at 11 09 51" src="https://github.com/zeng-yifei/STAG4D/assets/61124645/d1d2df79-c5b1-4177-83a5-041d8e9a9d68">

From here, how do i go about generating the 4D scene?

**Comment by zeng-yifei** [comment]
Are you using gui=True in your personal computer or a server? It can only turn on the GUI when using your PC.

Remember not to add `--` before `gui=True`. And the results are saved in the ply and pth files under `logs/xxx` when using `save_path=xxx`, so please try not to use `save_path=./`

**Comment by sam-motamed** [comment]
The issue is indeed that I am running via ssh and can't seem to get X11 forwarding to work. That's why I was wondering if I can run without gui and then render results after

**Comment by zeng-yifei** [comment]
OK, I will update a visualize code in the weekend.

Thank you for your feedback.

**Comment by sam-motamed** [comment]
I appreciate your help. Also, you might want to make a comment regarding  ```size``` in configs/stag4d.yaml which is currently set for the minions dataset size and wont work for custom datasets

**Comment by zeng-yifei** [comment]
I have updated the visualize script. You can now check it. Or maybe you want to personalize your own rendering scheme, then you can just modify the `save_rendering` function in `main.py` and 'visualize.py'.
